@echo off
echo Execution Started...
call mvn test -DsuiteXmlFile=testng.xml
echo Generating Allure report...
call mvn allure:report
echo Report generated at target/allure-reports
echo Copying report to shared folder...
xcopy /E /I /Y target\allure-reports Reports\latest-run
echo Done! Report is available at Reports\latest-run